name: build
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  c:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Compile
        run: |
          chmod +x scripts/build.sh
          ./scripts/build.sh
